steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --dockerfile=./jobs/download/Dockerfile
      - --destination=gcr.io/$PROJECT_ID/power-plant-2/download-job/:latest
      - --build-arg "AWS_ACCESS_KEY_ID=$_AWS_ACCESS_KEY_ID"
      - --build-arg "AWS_SECRET_ACCESS_KEY=$_AWS_SECRET_ACCESS_KEY"
      - --build-arg "AWS_DEFAULT_REGION=$_AWS_DEFAULT_REGION"
      - --build-arg "R2_CLIENT_ID=$_R2_CLIENT_ID"
      - --build-arg "DATABASE_URL=$_DATABASE_URL"
      - --build-arg "R2_PUBLIC_URL=$_R2_PUBLIC_URL"
      - --cache=true
substitutions:
  _AWS_ACCESS_KEY_ID: input
  _AWS_SECRET_ACCESS_KEY: input
  _AWS_DEFAULT_REGION: input
  _R2_CLIENT_ID: input
  _DATABASE_URL: input
  _R2_PUBLIC_URL: input
