version: "3.9"

services:
  webhook:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    environment:
      - R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
      - R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
      - R2_CLIENT_ID=$R2_CLIENT_ID
    entrypoint: ./entrypoint.sh
    command: yarn dev
    stdin_open: true
    tty: false
  cloudflared:
    image: cloudflare/cloudflared
    depends_on:
      - webhook
    command: tunnel --url http://webhook:3000

volumes:
  node_modules: